const flipkart = {
    header: [
      {
        headerLogo_icon:
          "https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png",
        headerLogo_p: "Explore",
        headerLogo_span: "Plus",
        headerLogo_plus:
          "https://static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/plus_aef861.png",
        searchBar_placeholder: "Search for products, brands and more ",
        searchBar_searchIcon: "assets/search-icon.svg",
        login: "Login",
        seller: "Become a Seller",
        More_span: "More",
        More_icon: "assets/down-arrow-nav.svg",
        cart_icon: "cart-icon.svg",
        cart_span: "Cart",
      },
    ],
  
    subNav: [
      {
        text: "Electronics",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "TVs & Appliances",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "Men",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "Women",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "BAby & Kids",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "Home & Furniture",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "Sports, Books & More",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "Flights",
        image: "assets/down-arrow-nav.svg",
      },
      {
        text: "Offer Zone",
        image: "assets/down-arrow-nav.svg",
      },
    ],
  
    left: {
      topDiv: [
        {
          head: "Filters",
          catHead: "CATEGORIES",
          greytxt: "Mobiles & Accessories",
          blacktxt: "Mobiles",
          image: "assets/down-arrow-nav.svg",
        },
      ],
      section1: [{
        title: "PRICE",
        min:["min","10000","15000","20000","30000"],
        max:["max","10000","15000","20000","30000","30000+"]
      }],
      section2: [
        {
          title: "BRAND",
          searchBarIcon: "searchBarIcon.svg",
          searchBarText: "Search Brand",
          options: ["SAMSUNG", "vivo", "OPPO", "realme", "POCO", "MOTOROLA"],
          more: "171 MORE",
        },
      ],
      section3: [
        {
          fLogo: "assets/fassured.png",
          question: "?",
        },
      ],
      section4: [
        {
          title: "CUSTOMER RATINGS",
          options: ["4★ & above", "3★ & above"],
          id: ["4", "3"],
        },
      ],
      section5: [
        {
          title: "GST INVOICE AVAILABLE",
          options: ["GST Invoice Available"],
        },
      ],
      section6: [
        {
          title: "RAM",
  
          options: [
            "4 GB",
            "3 GB",
            "2 GB",
            "1GB and Below",
            "8 GB and Above",
            "6 GB",
            "6 GB Above",
          ],
          id: ["4", "3","2","1+", "8+", "6", "6+"],
        },
      ],
      section7: [
        {
          title: "INTERNAL STORAGE",
  
          options: [
              "256 GB & Above",
              "128 - 255.9 GB",
              "64 - 127.9 GB",
              "32 - 63.9 GB",
              "16 - 31.9 GB",
              "8 - 15.9 GB",
              "4 - 7.9 GB",
              "2 GB - 3.9 GB",
              "1 GB - 1.9 GB",
              "Less than 1 GB",
              "256 GB Above",
          ],
        },
      ],
    },
  
    right: {
      div1: [
        {
          path: "Home > Mobiles & Appliances",
          result: "Showing 1 – 24 of 9,883 results for ",
          filters: [
            {
              text: "Sort By",
            },
            {
              text: "Relevence",
              cls: "relevence",
            },
            {
              text: "Popularity",
              cls: "popularity",
            },
            {
              text: "Price -- Low to High",
              cls: "lowtoHigh",
            },
            {
              text: "Price -- High to Low",
              cls: "hightoLow",
            },
            {
              text: "Newest First",
              cls: "newstFirst",
            },
          ],
        },
      ],
      rightSections: [
        {
          image:
            "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/a/c/k/-original-imagtc5fuzkvczr7.jpeg?q=70",
          name: "Apple iPhone 15",
          color: "Pink",
          storage: "128 GB",
          ratings: "4.6",
          ratingStar: "",
          Ratings: "46,372",
          reviews: "2,463",
          // RAM: "",
          display: "15.49 cm (6.1 inch) Super Retina XDR Display",
          cameras: "48MP + 12MP | 12MP Front Camera",
          processor: "A16 Bionic Chip, 6 Core Processor",
          warranty:
            "1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories",
          price: "81,999",
          originalPrice: "89900",
          discount: "8% off",
          delivery: "Free delivery",
          deal: "Saver Deal",
          specialOffers: "Save extra with combo offers",
          stock: "",
          fLogo: "assets/fassured.png",
          heart: "assets/grey-heart.svg",
          Date: "2024-08-10",
        },
        {
          image:
            "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/b/o/y/g04s-pb360000in-motorola-original-imahfc48vgh8yvgj.jpeg?q=70",
          name: "Motorola g04s",
          color: "Concord Black",
          storage: "64 GB",
          ratings: 4.2,
          ratingStar: "",
          reviews: 550,
          Ratings: 9783,
          RAM: "8 GB",
          expandable: "| Expandable Upto 1 TB",
          display: "16.76 cm (6.6 inch) HD+ Display",
          cameras: "50MP Rear Camera | 5MP Front Camera",
          battery: "5000 mAh Battery",
          processor: "T606 Processor",
          warranty: "1 Year on Handset and 6 Months on Accessories",
          price: "6,999",
          originalPrice: "9,999",
          discount: "30% off",
          delivery: "Free delivery",
          deal: "Saver Deal",
          specialOffers: "Upto ₹3,950 Off on Exchange",
          stock: "",
          fLogo: "assets/fassured.png",
          heart: "assets/grey-heart.svg",
          Date: "2024-06-10",
        },
        // {
        //   image:
        //     "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/c/4/d/-original-imaghx9qygjjg8hz.jpeg?q=70",
        //   name: "POCO M6 5G",
        //   color: "Galactic Black",
        //   rom: "128 GB",
        //   RAM:"6 GB",
        //   storage: "128 GB",
        //   ratings: 4.3,
        //   ratingStar: "",
        //   storage: "6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
        //   Ratings: "24,306",
        //   reviews: "1,287",
        //   display: "17.12 cm (6.74 inch) HD+ Display",
        //   cameras: "50MP Rear Camera | 8MP Front Camera",
        //   battery: "5000 mAh Battery",
        //   processor: "Mediatek Dimensity 6100+ Processor",
        //   warranty:
        //     "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories",
        //   price: "9,999",
        //   originalPrice: "13,999",
        //   discount: "28% off",
        //   delivery: "Free delivery",
        //   deal: "Saver Deal",
        //   specialOffers: "Upto ₹7,600 Off on Exchange",
        //   stock: "",
        //   fLogo: "assets/fassured.png",
        //   heart: "assets/grey-heart.svg",
        //   Date: "2024-04-10",
        // },
        // {
        //   image:
        //     "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/c/4/d/-original-imaghx9qygjjg8hz.jpeg?q=70",
        //   name: "POCO M6 5G",
        //   color: "Galactic Black",
        //   rom: "128 GB",
        //   storage: "128 GB",
        //   ratings: 3,
        //   ratingStar: "",
        //   RAM:"1 GB",
        //   storage: "6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
        //   Ratings: "24,306",
        //   reviews: "1,287",
        //   display: "17.12 cm (6.74 inch) HD+ Display",
        //   cameras: "50MP Rear Camera | 8MP Front Camera",
        //   battery: "5000 mAh Battery",
        //   processor: "Mediatek Dimensity 6100+ Processor",
        //   warranty:
        //     "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories",
        //   price: "101010",
        //   originalPrice: "13,999",
        //   discount: "28% off",
        //   delivery: "Free delivery",
        //   deal: "Saver Deal",
        //   specialOffers: "Upto ₹7,600 Off on Exchange",
        //   stock: "",
        //   fLogo: "assets/fassured.png",
        //   heart: "assets/grey-heart.svg",
        //   Date: "2024-04-10",
        // },
        {
            image: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/n/m/f/g34-5g-pb1v0002in-motorola-original-imagwu4rayqhgfjh.jpeg?q=70", 
            name: "Motorola G34 5G",
            color: "Ocean Green",
            storage: "128 GB",
            ratings: "4.2",
            ratingStar: "",
            Ratings: "1,15,570",
            reviews: "7,925",
            RAM: "8 GB",
            display: "16.51 cm (6.5 inch) HD+ Display",
            cameras: "50MP + 2MP | 16MP Front Camera",
            battery: "5000 mAh Battery",
            processor: "Snapdragon 695 5G Processor",
            warranty: "1 Year on Handset and 6 Months on Accessories",
            price: "11,999",
            originalPrice: "14,999",
            discount: "20% off",
            delivery: "Free delivery",
            deal: "Saver Deal",
            specialOffers: "Upto ₹8,400 Off on Exchange",
            stock: "",
            fLogo: "assets/fassured.png",
            heart: "assets/grey-heart.svg",
            Date: "2024-08-10", 
          },
          {
            image: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/n/l/3/-original-imah27wvna2g9hfc.jpeg?q=70",
            name: "vivo T3 Lite 5G",
            color: "Majestic Black",
            storage: "128 GB",
            ratings: "4.4",
            ratingStar: "",
            Ratings: "10,678",
            reviews: "359",
            RAM: "6 GB",
            expandable: "Expandable Upto 1 TB",
            display: "16.66 cm (6.56 inch) Display",
            cameras: "50MP + 2MP | 8MP Front Camera",
            battery: "5000 mAh Battery",
            processor: "Dimensity 6300 Processor",
            warranty: "1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories",
            price: "11,499",
            originalPrice: "15,499",
            discount: "25% off",
            delivery: "Free delivery",
            deal: "Top Discount of the Sale",
            specialOffers: "Upto ₹6,550 Off on Exchange",
            stock: "",
            fLogo: "assets/fassured.png",
            heart: "assets/grey-heart.svg",
            Date: "2024-08-10", 
          },
          {
            image: "https://rukminim2.flixcart.com/image/312/312/ktketu80/mobile/s/l/c/iphone-13-mlpf3hn-a-apple-original-imag6vzz5qvejz8z.jpeg?q=70",
            name: "Apple iPhone 13",
            color: "Midnight",
            storage: "128 GB",
            ratings: "4.6",
            ratingStar: "",
            Ratings: "2,83,503",
            reviews: "13,693",
            // RAM: "",
            display: "15.49 cm (6.1 inch) Super Retina XDR Display",
            cameras: "12MP + 12MP | 12MP Front Camera",
            processor: "A15 Bionic Chip Processor",
            warranty: "Brand Warranty for 1 Year",
            price: "51,999",
            originalPrice: "59,600",
            discount: "12% off",
            delivery: "Free delivery",
            deal: "Saver Deal",
            specialOffers: "Upto ₹30,200 Off on Exchange",
            stock: "",
            fLogo: "assets/fassured.png",
            heart: "assets/grey-heart.svg",
            Date: "2024-08-10",
          },
          // {
          //   image: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/m/e/3/-original-imah37gwn2xbvzhy.jpeg?q=70", 
          //   name: "OPPO K12x 5G with 45W SUPERVOOC Charger In-The-Box",
          //   color: "Breeze Blue",
          //   storage: "128 GB",
          //   ratings: "4.5",
          //   ratingStar: "",
          //   Ratings: "8,270",
          //   reviews: "169",
          //   RAM: "6 GB",
          //   expandable: "Expandable Upto 1 TB",
          //   display: "16.94 cm (6.67 inch) HD Display",
          //   cameras: "32MP + 2MP | 8MP Front Camera",
          //   battery: "5100 mAh Battery",
          //   processor: "Dimensity 6300 Processor",
          //   warranty: "1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories",
          //   price: "12,999",
          //   originalPrice: "16,999",
          //   discount: "23% off",
          //   delivery: "Free delivery",
          //   deal: "",
          //   specialOffers: "",
          //   stock: "",
          //   fLogo: "assets/fassured.png",
          //   heart: "assets/grey-heart.svg",
          //   Date: "2024-08-10", 
          // },
          {
            image: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/t/f/a/-original-imahfk4xp4xcggyt.jpeg?q=70",
            name: "REDMI 13C",
            color: "Starfrost White",
            storage: "128 GB",
            ratings: "4.3",
            ratingStar: "",
            Ratings: "35,710",
            reviews: "1,490",
            RAM: "4 GB",
            expandable: "Expandable Upto 1 TB",
            display: "17.12 cm (6.74 inch) HD+ Display",
            cameras: "50MP Rear Camera | 8MP Front Camera",
            battery: "5000 mAh Battery",
            processor: "Helio G85 Processor",
            warranty: "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories",
            price: "7,699",
            originalPrice: "11,999",
            discount: "35% off",
            delivery: "Free delivery",
            deal: "Saver Deal",
            specialOffers: "Upto ₹5,450 Off on Exchange",
            stock: "",
            fLogo: "assets/fassured.png",
            heart: "assets/grey-heart.svg",
            Date: "2024-08-10",
          }
      ],
    },
  };
  














  